paths:
  input_dir: "./input"
  output_dir: "./output"
  temp_dir: "./temp"
  logs_dir: "./logs"

processing:
  ocr_enabled: true
  ocr_language: "spa"
  max_file_size_mb: 50
  supported_formats: ["pdf","docx","doc"]
  table_detection_threshold: 0.5

normalization:
  remove_empty_rows: true
  remove_empty_columns: true
  handle_merged_cells: true

excel:
  include_header: true
  auto_adjust_width: true
  number_format:
    currency: "#,##0.00"
    percent: "0.00%"
  default_sheet_name: "Tabla_Extraida"
  templates:
    ficha_costo: "./config/template_ficha_costo.xlsx"

logging:
  level: "INFO"
  format: "json"
  rotation: "1 week"
  retention: "4 weeks"
  max_size: "100 MB"

streamlit:
  title: "Convertidor PDF/Word a Excel"
  icon: "📄"
  layout: "wide"

security:
  allowed_extensions: [".pdf", ".docx", ".doc"]
